name: Build and deploy


on:
  push:
    branches:
      - "master"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python version
        uses: actions/setup-python@v3.0.0
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'

      - name: Create and start virtual environment
        run: |
          python -m venv venv
          source venv/bin/activate

      - name: Install dependencies
        run: pip install -r requirements.txt
        
      # Optional: Add step to run tests here (PyTest, Django test suites, etc.)
      
      - name: zip files
        run: zip -r latest.zip .

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: latest
          path: latest.zip

  deploy:
    permissions:
      contents: none
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: python-app
          path: .
      - name: Install azcopy
        uses: kheiakiyama/install-azcopy-action@v1.0.3
        
      - run: azcopy_v10 --source latest.zip --destination ${{ secrets.MASTERSAS }} --recursive
        
